# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarMantenimiento'
    organization: 'sigevag2'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=*/.bin
      sonar.projectKey=ChristopherPirez_SIGEVA_MANTENIMIENTO---GRUPO-2
      sonar.projectName=SIGEVA_MANTENIMIENTO - GRUPO 2

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '*/surefire-reports/TEST-.xml'
    sonarQubeRunAnalysis: true
    goals: 'package'
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'